import React,{useEffect,useMemo,useState}from"react";
import{ArrowRight,Check,ChevronDown,Clock3,Mail,MapPin,Menu,Navigation,Phone,ShieldCheck,Truck,X,Zap}from"lucide-react";

const services=[["General Freight","Reliable movement of everyday commercial and palletised freight.",Truck],["Vehicle & Boat Transport","Secure transport for vehicles, boats and recreational equipment.",Navigation],["Heavy Haulage","Planned transport for heavy, oversized and specialised loads.",ShieldCheck]];
const fleet=[["General Freight",["Vans","Rigid Trucks","Curtain-Siders","Pantechs","Tray Trucks"]],["Heavy Haulage",["Flatbeds","Drop Decks","B-Doubles"]],["Specialised",["Tilt Trays","Low Loaders","Boat Trailers"]]];
const pallets=[[0,"No pallet"],[90,"Standard Pallet (117x117) — $90"],[130,"Heavy Pallet (500–1000kg) — $130"],[150,"Rack Pallet — $150"],[180,"Oversized Pallet — $180"]];
const vehicles=[["General Freight",[[2.2,"Van"],[3,"Rigid Truck"],[3.4,"Curtain-Sider"],[3.6,"Pantech"],[3.8,"Tray Truck"]]],["Heavy Haulage",[[4.5,"Flatbed"],[5,"Drop Deck"],[6.5,"B-Double"]]],["Specialised",[[4.8,"Tilt Tray"],[6,"Low Loader"],[5.5,"Boat Trailer"]]]];
const money=n=>"$"+Number(n||0).toFixed(2);
const go=p=>{history.pushState({},'',p);dispatchEvent(new PopStateEvent("popstate"));scrollTo({top:0,behavior:"smooth"})};
function usePath(){const[p,setP]=useState(location.pathname);useEffect(()=>{const f=()=>setP(location.pathname);addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);return p}

function Header(){const[open,setOpen]=useState(false);const section=h=>{setOpen(false);if(location.pathname!=="/"){go("/");setTimeout(()=>document.querySelector(h)?.scrollIntoView({behavior:"smooth"}),80)}else document.querySelector(h)?.scrollIntoView({behavior:"smooth"})};return <header className="header"><div className="nav"><button className="brand" onClick={()=>go("/")}><b>LK</b><span><strong>LOWKI</strong><small>TRANSPORT</small></span></button><div className={open?"links open":"links"}>{[["Services","#services"],["Fleet","#fleet"],["Contact","#contact"]].map(([x,h])=><button key={x} onClick={()=>section(h)}>{x}</button>)}<button className="navquote" onClick={()=>{setOpen(false);go("/quote")}}>Get Quote <ArrowRight size={16}/></button></div><button className="menubtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}

function Hero(){return <section className="hero"><div className="glow"/><div className="container heroGrid"><div><div className="eyebrow"><i/> MELBOURNE BASED · VICTORIA & INTERSTATE</div><h1>LOWKI<br/><em>TRANSPORT</em></h1><p>Lowki Transport is a Melbourne-based premium transport and logistics provider delivering reliable, secure, and efficient freight solutions across Victoria and interstate. Built on precision, professionalism, and performance, we handle everything from general freight to specialised and time-critical consignments.</p><div className="actions"><button className="primary" onClick={()=>go("/quote")}>Get a Quote <ArrowRight/></button><button className="ghost" onClick={()=>document.querySelector("#services")?.scrollIntoView({behavior:"smooth"})}>Our Services <ChevronDown/></button></div><div className="trust"><span><Check/> Reliable freight</span><span><Check/> Secure handling</span><span><Check/> Melbourne based</span></div></div><div className="heroCard"><span className="redline"/><small>LOWKI LOGISTICS</small><h2>Precision from pickup to delivery.</h2><p>Professional transport solutions designed around your freight, schedule and delivery requirements.</p><div className="stats"><b>VIC<small>Based</small></b><b>24/7<small>Scheduling</small></b><b>100%<small>Focused</small></b></div></div></div></section>}

function Services(){return <section id="services" className="section"><div className="container"><div className="sectionHead"><div><label>WHAT WE DO</label><h2>Our Services</h2></div><p>Transport capability built around dependable execution, clear communication and the right equipment for the job.</p></div><div className="cards">{services.map(([t,d,I])=><article className="card" key={t}><span className="icon"><I/></span><h3>{t}</h3><p>{d}</p><button onClick={()=>go("/quote")}>Request a quote <ArrowRight/></button></article>)}</div></div></section>}

function Fleet(){return <section id="fleet" className="section dark"><div className="container"><div className="sectionHead"><div><label>CAPABILITY</label><h2>Fleet & Capability</h2></div><p>A structured and scalable fleet supporting general freight, heavy haulage, interstate logistics, and specialised transport operations.</p></div><div className="cards">{fleet.map(([t,items],i)=><article className="fleet" key={t}><span className="number">0{i+1}</span><h3>{t}</h3><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><button onClick={()=>go("/quote")}>Get pricing <ArrowRight/></button></article>)}</div></div></section>}

function Contact(){const email="info@lowkitransport.com",mail=`mailto:${email}?subject=Lowki%20Transport%20Enquiry`;return <section id="contact" className="section contact"><div className="container contactGrid"><div><label>CONTACT</label><h2>Get Moving With Lowki</h2><p>Quick responses. Reliable service. Trusted delivery.</p><div className="contactList"><a href={mail}><i><Mail/></i><span>Email<strong>{email}</strong></span></a><div><i><MapPin/></i><span>Location<strong>Melbourne, Victoria</strong></span></div></div></div><div className="contactCard"><div className="kicker"><Zap/> READY TO MOVE?</div><h3>Tell us what you're transporting.</h3><p>Use the online quote calculator to get an estimate and prepare your booking request.</p><button className="primary full" onClick={()=>go("/quote")}>Start a Quote <ArrowRight/></button><a href={mail}>Or email {email}</a></div></div></section>}

function Footer(){return <footer><div className="container foot"><button className="brand" onClick={()=>go("/")}><b>LK</b><span><strong>LOWKI</strong><small>TRANSPORT</small></span></button><span>© {new Date().getFullYear()} Lowki Transport. All rights reserved.</span><button onClick={()=>go("/quote")}>Get Quote <ArrowRight/></button></div></footer>}

function Field({label,children,wide}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}</label>}
function Quote(){
const[pickup,setPickup]=useState(""),[drop,setDrop]=useState(""),[freight,setFreight]=useState("weight"),[weight,setWeight]=useState(100),[palletRate,setPalletRate]=useState(0),[palletQty,setPalletQty]=useState(1),[urgent,setUrgent]=useState(false),[cust,setCust]=useState(false),[manualKm,setManualKm]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[quote,setQuote]=useState(null),[client,setClient]=useState({name:"",email:"",phone:"",notes:""});
async function geo(a){let r=await fetch("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=au&q="+encodeURIComponent(a));if(!r.ok)throw Error();let d=await r.json();if(!d[0])throw Error();return[+d[0].lat,+d[0].lon]}
async function calc(){
if(!pickup.trim()||!drop.trim()){setStatus("Please enter both addresses.");return}
if(freight==="weight"&&!Number(weight)){setStatus("Please enter the freight weight.");return}
setBusy(true);setQuote(null);setStatus("Working out your route…");
try{
let km=Number(manualKm);
if(!km){let a=await geo(pickup),b=await geo(drop),r=await fetch("https://router.project-osrm.org/route/v1/driving/"+a[1]+","+a[0]+";"+b[1]+","+b[0]+"?overview=false");if(!r.ok)throw Error();let d=await r.json();if(!d.routes?.[0])throw Error();km=d.routes[0].distance/1000}
let palletTotal=freight==="pallet"?Number(palletRate)*Number(palletQty||0):0;
let extras=urgent?100:0;
let total=cust?Math.max(90,palletTotal):Math.max(90,80+km*10+palletTotal+extras);
setQuote({total,km,palletTotal,extras});setStatus("Quote ready");
}catch(e){setStatus("We couldn't find the route. Try a full address, suburb and postcode.");setQuote(null)}
finally{setBusy(false)}
}
function summary(){return["LOWKI TRANSPORT — BOOKING REQUEST","",`Customer: ${client.name||"Not provided"}`,`Email: ${client.email||"Not provided"}`,`Phone: ${client.phone||"Not provided"}`,`Pickup: ${pickup}`,`Delivery: ${drop}`,`Freight: ${freight==="pallet"?"Pallet freight":"General freight"}`,`Weight: ${weight} kg`,`Pallet: ${freight==="pallet"?palletRate+" × "+palletQty:"None"}`,`Urgent same-day: ${urgent?"Yes":"No"}`,`Customer Pickup: ${cust?"Yes":"No"}`,`Distance: ${quote?.km?.toFixed(1)||"N/A"} km`,`Estimated Quote: ${money(quote?.total)}`,"",`Notes: ${client.notes||"None"}`].join("\\n")}
function send(){if(!client.name||!client.email||!client.phone||!quote){alert("Please enter your name, email and phone, then calculate your quote first.");return}location.href="mailto:info@lowkitransport.com?subject="+encodeURIComponent("Lowki Transport Booking Request")+"&body="+encodeURIComponent(summary())}
return <div className="quotePage"><div className="quoteTop container"><button onClick={()=>go("/")}>← Lowki Transport</button><span>ONLINE QUOTE</span></div><main className="container quoteMain">
<div className="quoteIntro"><label>LOWKI TRANSPORT</label><h1>Get a quote in under a minute.</h1><p>Just enter where it's going and what you're moving. We'll calculate an estimated delivery price.</p></div>
<div className="quoteGrid"><div className="quoteForm">
<QSec title="1 · Your route"><div className="formGrid"><Field label="Pickup address" wide><input value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="Street, suburb & postcode"/></Field><Field label="Delivery address" wide><input value={drop} onChange={e=>setDrop(e.target.value)} placeholder="Street, suburb & postcode"/></Field></div><p className="note">Tip: Full addresses give the most accurate distance.</p></QSec>
<QSec title="2 · Your freight"><div className="formGrid"><Field label="What are you moving?"><select value={freight} onChange={e=>setFreight(e.target.value)}><option value="weight">General freight</option><option value="pallet">Pallet freight</option></select></Field><Field label="Weight (kg)"><input type="number" min="1" value={weight} onChange={e=>setWeight(e.target.value)}/></Field>{freight==="pallet"&&<><Field label="Pallet type"><select value={palletRate} onChange={e=>setPalletRate(+e.target.value)}>{pallets.filter(x=>x[0]>0).map(([v,n])=><option value={v} key={n}>{n}</option>)}</select></Field><Field label="Quantity"><input type="number" min="1" value={palletQty} onChange={e=>setPalletQty(e.target.value)}/></Field></>}</div></QSec>
<QSec title="3 · Service options"><CheckBox checked={urgent} onChange={setUrgent} title="Urgent same-day" sub="+$100"/><CheckBox checked={cust} onChange={setCust} title="Customer Pickup" sub="Pallet pricing only"/></QSec>
<button className="calculate" disabled={busy} onClick={calc}>{busy?"Calculating your route…":"Calculate My Quote"} <ArrowRight/></button>
{status&&<div className="route"><Navigation/> {status}</div>}
{quote&&<div className="result"><label>YOUR ESTIMATED PRICE</label><strong>{money(quote.total)}</strong><small>{cust?"Customer pickup · pallet charge only":`$40 pickup · $40 delivery · ${money(quote.km*10)} distance${quote.extras?" · $100 urgent":""}`}</small></div>}
{!quote&&<p className="disclaimer">Estimates are based on the information entered. Final pricing may vary depending on access, dimensions, weight and delivery requirements.</p>}
{quote&&<QSec title="4 · Ready to book?"><div className="formGrid"><Field label="Full name"><input value={client.name} onChange={e=>setClient({...client,name:e.target.value})} placeholder="Your name"/></Field><Field label="Email"><input type="email" value={client.email} onChange={e=>setClient({...client,email:e.target.value})} placeholder="you@example.com"/></Field><Field label="Phone"><input value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})} placeholder="04xx xxx xxx"/></Field><Field label="Notes" wide><textarea rows="3" value={client.notes} onChange={e=>setClient({...client,notes:e.target.value})} placeholder="Access, delivery times or special instructions"/></Field></div><button className="calculate" onClick={send}>Send Booking Request <Mail/></button></QSec>}
</div><aside><div className="side"><ShieldCheck/><h3>Simple. Fast. Clear.</h3><p>Enter your route and freight details, calculate your estimate, then send the request straight to Lowki Transport.</p><ul><li><Check/> $40 pickup</li><li><Check/> $40 delivery</li><li><Check/> $10/km</li><li><Check/> $90 minimum</li></ul><a href="mailto:info@lowkitransport.com?subject=Lowki%20Transport%20Enquiry" className="outline">Email Lowki <Mail/></a></div></aside></div></main></div>}
function vehicleName(r){for(const[,o]of vehicles){let f=o.find(x=>x[0]===+r);if(f)return f[1]}return"Selected vehicle"}
function QSec({title,children}){return <section className="qsec"><h2>{title}</h2>{children}</section>}
function CheckBox({checked,onChange,title,sub}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span><b>{title}</b><small>{sub}</small></span></label>}
function App(){return usePath()==="/quote"?<Quote/>:<><Header/><Hero/><Services/><Fleet/><Contact/><Footer/></>}
export default App;