import React,{useEffect,useMemo,useState}from"react";
import{ArrowRight,Check,ChevronDown,Clock3,Mail,MapPin,Menu,Navigation,Phone,ShieldCheck,Truck,X,Zap}from"lucide-react";

const services=[["General Freight","Reliable movement of everyday commercial and palletised freight.",Truck],["Vehicle & Boat Transport","Secure transport for vehicles, boats and recreational equipment.",Navigation],["Heavy Haulage","Planned transport for heavy, oversized and specialised loads.",ShieldCheck]];
const fleet=[["General Freight",["Vans","Rigid Trucks","Curtain-Siders","Pantechs","Tray Trucks"]],["Heavy Haulage",["Flatbeds","Drop Decks","B-Doubles"]],["Specialised",["Tilt Trays","Low Loaders","Boat Trailers"]]];
const pallets=[[0,"No pallet"],[90,"Standard Pallet (117x117) — $90"],[130,"Heavy Pallet (500–1000kg) — $130"],[150,"Rack Pallet — $150"],[180,"Oversized Pallet — $180"]];
const vehicles=[["General Freight",[[2.2,"Van"],[3,"Rigid Truck"],[3.4,"Curtain-Sider"],[3.6,"Pantech"],[3.8,"Tray Truck"]]],["Heavy Haulage",[[4.5,"Flatbed"],[5,"Drop Deck"],[6.5,"B-Double"]]],["Specialised",[[4.8,"Tilt Tray"],[6,"Low Loader"],[5.5,"Boat Trailer"]]]];
const money=n=>"$"+Number(n||0).toFixed(2);
const go=p=>{history.pushState({},'',p);dispatchEvent(new PopStateEvent("popstate"));scrollTo({top:0,behavior:"smooth"})};
function usePath(){const[p,setP]=useState(location.pathname);useEffect(()=>{const f=()=>setP(location.pathname);addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);return p}

function Header(){const[open,setOpen]=useState(false);const section=h=>{setOpen(false);if(location.pathname!=="/"){go("/");setTimeout(()=>document.querySelector(h)?.scrollIntoView({behavior:"smooth"}),80)}else document.querySelector(h)?.scrollIntoView({behavior:"smooth"})};return <header className="header"><div className="nav"><button className="brand" onClick={()=>go("/")}><b>LK</b><span><strong>LOWKI</strong><small>TRANSPORT</small></span></button><div className={open?"links open":"links"}>{[["Services","#services"],["Fleet","#fleet"],["Contact","#contact"]].map(([x,h])=><button key={x} onClick={()=>section(h)}>{x}</button>)}<button className="navquote" onClick={()=>{setOpen(false);go("/quote")}}>Get Quote <ArrowRight size={16}/></button></div><button className="menubtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}

function Hero(){return <section className="hero"><div className="glow"/><div className="container heroGrid"><div><div className="eyebrow"><i/> MELBOURNE BASED · VICTORIA & INTERSTATE</div><h1>LOWKI<br/><em>TRANSPORT</em></h1><p>Lowki Transport is a Melbourne-based premium transport and logistics provider delivering reliable, secure, and efficient freight solutions across Victoria and interstate. Built on precision, professionalism, and performance, we handle everything from general freight to specialised and time-critical consignments.</p><div className="actions"><button className="primary" onClick={()=>go("/quote")}>Get a Quote <ArrowRight/></button><button className="ghost" onClick={()=>document.querySelector("#services")?.scrollIntoView({behavior:"smooth"})}>Our Services <ChevronDown/></button></div><div className="trust"><span><Check/> Reliable freight</span><span><Check/> Secure handling</span><span><Check/> Melbourne based</span></div></div><div className="heroCard"><span className="redline"/><small>LOWKI LOGISTICS</small><h2>Precision from pickup to delivery.</h2><p>Professional transport solutions designed around your freight, schedule and delivery requirements.</p><div className="stats"><b>VIC<small>Based</small></b><b>24/7<small>Scheduling</small></b><b>100%<small>Focused</small></b></div></div></div></section>}

function Services(){return <section id="services" className="section"><div className="container"><div className="sectionHead"><div><label>WHAT WE DO</label><h2>Our Services</h2></div><p>Transport capability built around dependable execution, clear communication and the right equipment for the job.</p></div><div className="cards">{services.map(([t,d,I])=><article className="card" key={t}><span className="icon"><I/></span><h3>{t}</h3><p>{d}</p><button onClick={()=>go("/quote")}>Request a quote <ArrowRight/></button></article>)}</div></div></section>}

function Fleet(){return <section id="fleet" className="section dark"><div className="container"><div className="sectionHead"><div><label>CAPABILITY</label><h2>Fleet & Capability</h2></div><p>A structured and scalable fleet supporting general freight, heavy haulage, interstate logistics, and specialised transport operations.</p></div><div className="cards">{fleet.map(([t,items],i)=><article className="fleet" key={t}><span className="number">0{i+1}</span><h3>{t}</h3><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><button onClick={()=>go("/quote")}>Get pricing <ArrowRight/></button></article>)}</div></div></section>}

function Contact(){const email="info@lowkitransport.com",mail=`mailto:${email}?subject=Lowki%20Transport%20Enquiry`;return <section id="contact" className="section contact"><div className="container contactGrid"><div><label>CONTACT</label><h2>Get Moving With Lowki</h2><p>Quick responses. Reliable service. Trusted delivery.</p><div className="contactList"><a href={mail}><i><Mail/></i><span>Email<strong>{email}</strong></span></a><div><i><MapPin/></i><span>Location<strong>Melbourne, Victoria</strong></span></div></div></div><div className="contactCard"><div className="kicker"><Zap/> READY TO MOVE?</div><h3>Tell us what you're transporting.</h3><p>Use the online quote calculator to get an estimate and prepare your booking request.</p><button className="primary full" onClick={()=>go("/quote")}>Start a Quote <ArrowRight/></button><a href={mail}>Or email {email}</a></div></div></section>}

function Footer(){return <footer><div className="container foot"><button className="brand" onClick={()=>go("/")}><b>LK</b><span><strong>LOWKI</strong><small>TRANSPORT</small></span></button><span>© {new Date().getFullYear()} Lowki Transport. All rights reserved.</span><button onClick={()=>go("/quote")}>Get Quote <ArrowRight/></button></div></footer>}

function Field({label,children,wide}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}</label>}
function Quote(){
const[freight,setFreight]=useState("weight"),[weight,setWeight]=useState(100),[pickup,setPickup]=useState(""),[drop,setDrop]=useState(""),[rows,setRows]=useState([{rate:0,qty:1}]),[urgent,setUrgent]=useState(false),[cust,setCust]=useState(false),[distance,setDistance]=useState(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[quote,setQuote]=useState(null),[client,setClient]=useState({name:"",email:"",phone:"",notes:""});
async function geo(a){let r=await fetch("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=au&q="+encodeURIComponent(a));if(!r.ok)throw Error();let d=await r.json();if(!d[0])throw Error();return[+d[0].lat,+d[0].lon]}
async function calc(){
if(!pickup.trim()||!drop.trim()){setStatus("Enter both pickup and delivery addresses.");return}
setBusy(true);setStatus("Calculating your route…");
try{
let a=await geo(pickup),b=await geo(drop),r=await fetch(`https://router.project-osrm.org/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?overview=false`),d=await r.json();
if(!d.routes?.[0])throw Error();
let km=d.routes[0].distance/1000;setDistance(km);
let palletTotal=rows.reduce((s,x)=>s+x.rate*x.qty,0),extras=urgent?100:0,total=cust?palletTotal:Math.max(90,80+km*10+palletTotal+extras);
setQuote({total,km,palletTotal,extras});setStatus(`${km.toFixed(1)} km route • estimate ready`);
}catch(e){setDistance(null);setStatus("We couldn't calculate the route. Check the addresses and try again.");setQuote(null)}
finally{setBusy(false)}
}
function summary(){return["LOWKI TRANSPORT — BOOKING REQUEST","",`Customer: ${client.name||"Not provided"}`,`Email: ${client.email||"Not provided"}`,`Phone: ${client.phone||"Not provided"}`,`Pickup: ${pickup||"Not provided"}`,`Delivery: ${drop||"Not provided"}`,`Freight: ${freight==="pallet"?"Pallet freight":"Weight-based freight"}`,`Weight: ${weight} kg`,`Customer Pickup: ${cust?"Yes":"No"}`,`Urgent same-day: ${urgent?"Yes":"No"}`,`Estimated Quote: ${money(quote?.total)}`,"",`Notes: ${client.notes||"None"}`].join("\\n")}
function send(){if(!client.name||!client.email||!client.phone||!quote){alert("Please complete your details and calculate your quote first.");return}location.href=`mailto:info@lowkitransport.com?subject=${encodeURIComponent("Lowki Transport Booking Request")}&body=${encodeURIComponent(summary())}`}
return <div className="quotePage"><div className="quoteTop container"><button onClick={()=>go("/")}>← Lowki Transport</button><span>GET A QUOTE</span></div><main className="container quoteMain">
<div className="quoteIntro"><label>LOWKI TRANSPORT</label><h1>Get your freight estimate.</h1><p>Enter the essentials below. Most quotes take less than a minute.</p></div>
<div className="quoteGrid"><div className="quoteForm">
<QSec title="1 · Where is it going?"><div className="formGrid"><Field label="Pickup address" wide><input value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="e.g. Dandenong, VIC"/></Field><Field label="Delivery address" wide><input value={drop} onChange={e=>setDrop(e.target.value)} placeholder="e.g. Melbourne Airport, VIC"/></Field></div></QSec>
<QSec title="2 · What are you moving?"><div className="formGrid"><Field label="Freight type"><select value={freight} onChange={e=>setFreight(e.target.value)}><option value="weight">General freight</option><option value="pallet">Pallet freight</option></select></Field><Field label="Weight (kg)"><input type="number" min="0" value={weight} onChange={e=>setWeight(e.target.value)}/></Field><Field label="Pallets"><select value={rows[0].rate} onChange={e=>setRows([{rate:+e.target.value,qty:rows[0].qty}])}>{pallets.map(([v,n])=><option value={v} key={n}>{n}</option>)}</select></Field>{rows[0].rate>0&&<Field label="Quantity"><input type="number" min="1" value={rows[0].qty} onChange={e=>setRows([{...rows[0],qty:+e.target.value}])}/></Field>}</div></QSec>
<QSec title="3 · Any extras?"><CheckBox checked={urgent} onChange={setUrgent} title="Urgent same-day" sub="+$100"/><CheckBox checked={cust} onChange={setCust} title="Customer Pickup" sub="Pallet pricing only"/></QSec>
<button className="calculate" disabled={busy} onClick={calc}>{busy?"Calculating…":"Calculate My Quote"} <ArrowRight/></button>
{status&&<div className="route"><Navigation/> {status}</div>}
{quote&&<div className="result"><label>ESTIMATED TOTAL</label><strong>{money(quote.total)}</strong><small>{cust?"Customer Pickup: pallet charge only":`Pickup $40 · Delivery $40 · Distance ${money(quote.km*10)} · Extras ${money(quote.extras)}`}</small></div>}
<QSec title="4 · Send the booking request"><div className="formGrid"><Field label="Full name"><input value={client.name} onChange={e=>setClient({...client,name:e.target.value})} placeholder="Your name"/></Field><Field label="Email"><input type="email" value={client.email} onChange={e=>setClient({...client,email:e.target.value})} placeholder="you@example.com"/></Field><Field label="Phone"><input value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})} placeholder="04xx xxx xxx"/></Field><Field label="Notes" wide><textarea rows="3" value={client.notes} onChange={e=>setClient({...client,notes:e.target.value})} placeholder="Anything we should know?"/></Field></div><button className="calculate" onClick={send}>Send Booking Request <Mail/></button><p className="disclaimer">Estimate only. Final pricing can vary with access, dimensions, weight and delivery requirements.</p></QSec>
</div><aside><div className="side"><ShieldCheck/><h3>Simple pricing.</h3><p>Route-based estimate using your pickup, delivery and selected freight options.</p><ul><li><Check/> $40 pickup</li><li><Check/> $40 delivery</li><li><Check/> $10/km</li><li><Check/> $90 minimum</li></ul><a href="mailto:info@lowkitransport.com?subject=Lowki%20Transport%20Enquiry" className="outline">Email Lowki <Mail/></a></div></aside></div></main></div>}
function vehicleName(r){for(const[,o]of vehicles){let f=o.find(x=>x[0]===+r);if(f)return f[1]}return"Selected vehicle"}
function QSec({title,children}){return <section className="qsec"><h2>{title}</h2>{children}</section>}
function CheckBox({checked,onChange,title,sub}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span><b>{title}</b><small>{sub}</small></span></label>}
function App(){return usePath()==="/quote"?<Quote/>:<><Header/><Hero/><Services/><Fleet/><Contact/><Footer/></>}
export default App;